version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - 27020:27017
    environment:
      MONGO_INITBD_ROOT_USERNAME: root
      MONGO_INITBD_ROOT_PASSWORD: password
      MONGO_INITBD_DATABASE: product-service
    volumes:
      - ./data/mongodb:/data/db